In [1]:
import pandas as pd
df = pd.read_csv("/Users/somitagarwal/Desktop/Python/Day 72/salaries_by_college_major.csv")

In [3]:
df.shape #to see number of columns and rows in our data it comes in the manner (rows, columns)

(51, 6)

In [5]:
df.columns # ye hume saare columns ke naam deta hai

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [7]:
df.isna() # ye hume saari blank cells dega aur sath hi mein wo bhi return karega jaha pe strings hongi 
# instead of numbers

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [9]:
df.tail() #last ki 5 rows ko dekhne ke liye tail ka use hota hai

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [11]:
# hume iss last row ki zarurat nhi hai kyuki ye humare data ke hisab se koi value nhi provide kr rhi hai
# to hum ise drop(delete) kr denge
clean_df = df.dropna()

In [13]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [15]:
clean_df.shape

(50, 6)

In [17]:
# To access a particular column from a data frame
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [19]:
# To find the highest starting salary 
clean_df['Starting Median Salary'].max()

74300.0

In [21]:
# to check the id of the max salary
clean_df['Starting Median Salary'].idxmax()

43

In [23]:
# To see the name of the major that corresponds to that particular row
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [25]:
# or we can also write it as
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [27]:
# agar hum .loc mein koi particular column nhi mention krte hai to wo hume poori row nikal ke de dega
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [29]:
clean_df[43]

KeyError: 43

In [68]:
# Question 1 - What college major has the highest mid-career salary? How much do graduates with this major earn? (Mid-career is defined as having 10+ years of experience).

print(clean_df['Mid-Career Median Salary'].max())
print(clean_df['Mid-Career Median Salary'].idxmax())
print(clean_df['Undergraduate Major'][8])

107000.0
8
Chemical Engineering

In [72]:
# Question 2 - Which college major has the lowest starting salary and how much do graduates earn after university?

print(clean_df['Starting Median Salary'].min())
print(clean_df['Starting Median Salary'].idxmin())
print(clean_df['Undergraduate Major'][49])

34000.0
49
Spanish

In [76]:
# Question 3 - Which college major has the lowest mid-career salary and how much can people expect to earn with this degree? 

print(clean_df['Mid-Career Median Salary'].min())
print(clean_df['Mid-Career Median Salary'].idxmin())
print(clean_df['Undergraduate Major'][18])

52000.0
18
Education

In [80]:
difference_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
# hume chahe to ise aise bhi likh skte the
# Difference_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary']) 
print(difference_col)

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [83]:
clean_df.insert(1, "Difference", difference_col)

In [85]:
clean_df.head()

,Undergraduate Major,Difference,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [95]:
low_risk = clean_df.sort_values("Difference") # difference column ke base pe hum sort kr rhe hai
# ye by default ascending mein hi krega but agar hume descending mein karana hai to hume aisa likhna hoga 
# low_risk = clean_df.sort_values("Difference",ascending=False) ab ye descending mein arrange karega

In [93]:
print(low_risk[['Undergraduate Major','Difference']].head())

           Undergraduate Major  Difference
40                     Nursing     50700.0
43         Physician Assistant     57600.0
41                   Nutrition     65300.0
49                     Spanish     65400.0
27  Health Care Administration     66400.0

In [101]:
# Question 4 - Using the .sort_values() method, can you find the degrees with the highest potential? Find the top 5 degrees with the highest values in the 90th percentile. abs

answer4 = clean_df.sort_values('Mid-Career 90th Percentile Salary',ascending= False)

In [103]:
answer4[['Undergraduate Major','Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [119]:
# Question 5 - find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation 

answer5a = clean_df.sort_values('Difference',ascending=False)

In [121]:
answer5a[['Undergraduate Major','Difference']].head()

   Undergraduate Major  Difference
17           Economics    159400.0
22             Finance    147800.0
37                Math    137800.0
36           Marketing    132900.0
42          Philosophy    132500.0

In [125]:
answer5b = clean_df.sort_values('Mid-Career Median Salary', ascending=False)

In [129]:
answer5b[['Undergraduate Major', 'Mid-Career Median Salary']].head()

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

In [131]:
# Grouping and Pivoting Data with Pandas

In [152]:
clean_df.groupby('Group').count()

,Undergraduate Major,Difference,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [154]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean(numeric_only=True)

,Difference,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"